logging:
  level: DEBUG
  appenders:
    - type: console
      threshold: INFO
      timeZone: IST
      logFormat: "[%date] [%-5level] [%thread] [%X{id}] [%logger{10}] [%msg]%n"
    - type: file
      threshold: INFO
      timeZone: IST
      logFormat: "[%date] [%-5level] [%thread] [%X{id}] [%logger{10}] [%msg]%n"
      currentLogFilename: /var/log/gmp-v3/services-info.log
      archive: true
      archivedLogFilenamePattern: /var/log/gmp-v3/services-info-%d{yyyy-MM-dd}.log.gz
      archivedFileCount: 50
    - type: file
      threshold: ERROR
      timeZone: IST
      logFormat: "[%date] [%-5level] [%thread] [%X{id}] [%logger{10}] [%msg]%n"
      currentLogFilename: /var/log/gmp-v3/services-error.log
      archive: true
      archivedLogFilenamePattern: /var/log/gmp-v3/services-error-%d{yyyy-MM-dd}.log.gz
      archivedFileCount: 50

database:
  # the name of your JDBC driver
  driverClass: com.mysql.jdbc.Driver

  # the username
  user: root

  # the password
  password: gmp2016

  # the JDBC URL
  url: jdbc:mysql://52.77.1.60:3306/

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connections liveness
  validationQuery: "/* MyService Health Check */ SELECT 1"

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 32

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

flyway:
  # The encoding of SQL migrations. (default: UTF-8)
  encoding: UTF-8
  # The schemas managed by Flyway. (default: default schema of the connection)
  schemas:
    - get_my_parking_v2
  # The name of the schema metadata table that will be used by Flyway. (default: schema_version)
  metaDataTableName: schema_version
  # The file name prefix for sql migrations (default: V)
  sqlMigrationPrefix: V
  # The file name separator for sql migrations (default: __)
  sqlMigrationSeparator: __
  # The file name suffix for sql migrations (default: .sql)
  sqlMigrationSuffix: .sql
  # The prefix of every placeholder. (default: ${ )
  locations:
    - db/migration