os: linux
files:
  - source: /
    destination: ~/
  - source: package/var/log/gmp
    destination: /var/log/gmp
permissions:
  - object: /var/log/gmp
    pattern: "*.log"
    owner: ubuntu
    mode: 644
    type:
      - file
hooks:
  BeforeInstall:
    - location: package/scripts/preInstall.sh
  ApplicationStart:
    - location: package/scripts/run.sh
      timeout: 3600