#!/bin/sh
PIDFILE=/var/run/gmp-v3-migration.pid
set -e

case "$1" in
    configure)
	if [ -d "/etc/monit/" ]; then
		monit stop gmp-v3
		/etc/init.d/gmp-v3-migration start
		PID=`cat $PIDFILE`
		wait $PID
		monit start gmp-v3
	else
		/etc/init.d/gmp-v3 stop
		/etc/init.d/gmp-v3-migration start
		PID=`cat $PIDFILE`
        wait $PID
		/etc/init.d/gmp-v3 start
	fi
    ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
exit 0
