#!/bin/bash

java  -Xms512m -Xmx512m -Xloggc:/var/log/gmp-v3/gc.out -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=9002 -Dcom.sun.management.jmxremote.authenticate=false -jar /usr/share/gmp-v3/getMyParking-0.0.1.jar db migrate /usr/share/gmp-v3/migration_config.yaml && java  -Xms512m -Xmx512m -Xloggc:/var/log/gc.out -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=9002 -Dcom.sun.management.jmxremote.authenticate=false -jar /usr/share/gmp-v3/getMyParking-0.0.1.jar server /usr/share/gmp-v3/config.yaml 2>1&
