#!/bin/bash

java  -Xms512m -Xmx512m -Xloggc:/var/log/gmp/gc.out -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=8083 -Dcom.sun.management.jmxremote.authenticate=false -jar /usr/share/gmp/getMyParking-0.0.1.jar db migrate /usr/share/gmp/migration_config.yaml && java  -Xms512m -Xmx512m -Xloggc:/var/log/gc.out -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=8083 -Dcom.sun.management.jmxremote.authenticate=false -jar /usr/share/gmp/getMyParking-0.0.1.jar server /usr/share/gmp/config.yaml > /tmp/null
